langDict = {
    "ar_SA":{
        "Add":"أضف",
        "Remove":"إزالة",
        "Open":"فتح",
        "Play":"تشغيل",
        "Stop":"إيقاف",
        "List":"قائمة",
        "Party":"حفلة",
        "Save Playlist":"حفظ قائمة التشغيل",
        "Open Playlist":"فتح قائمة التشغيل",
        "Playlist is empty":"قائمة التشغيل فارغة",
        "Playlist saved":"تم حفظ قائمة التشغيل",
        "Playlist loaded":"تم تحميل قائمة التشغيل",
        "Save error":"خطأ في الحفظ",
        "Open error":"خطأ في الفتح",
        "Add Media":"أضف وسائط",
        "Add Link":"أضف رابط",
        "Enter Media URL:":"أدخل رابط الوسائط:",
        "Pause":"إيقاف مؤقت"
    },
    "hy_AM":{
        "Add":"Ավելացնել",
        "Remove":"Ջնջել",
        "Open":"Բացել",
        "Play":"Սկսել",
        "Stop":"Կանգնեցնել",
        "List":"Ցանկ",
        "Party":"Կուսակցություն",
        "Save Playlist":"Պահպանել նվագարկիչը",
        "Open Playlist":"Բացել նվագարկիչը",
        "Playlist is empty":"Նվագարկիչը դատարկ է",
        "Playlist saved":"Նվագարկիչը պահպանվեց",
        "Playlist loaded":"Նվագարկիչը բեռնվել է",
        "Save error":"Պահպանում սխալ",
        "Open error":"Բացման սխալ",
        "Add Media":"Ավելացնել մեդիա",
        "Add Link":"Ավելացնել հղում",
        "Enter Media URL:":"Մուտքագրեք մեդիայի URL-ը:",
        "Pause":"Կանգնեցնել"
    },
    "az_AZ":{
        "Add":"Əlavə et",
        "Remove":"Sil",
        "Open":"Aç",
        "Play":"Oynat",
        "Stop":"Dayandır",
        "List":"Siyahı",
        "Party":"Parti",
        "Save Playlist":"Pleylisti yadda saxla",
        "Open Playlist":"Pleylisti aç",
        "Playlist is empty":"Pleylist boşdur",
        "Playlist saved":"Pleylist yadda saxlanıldı",
        "Playlist loaded":"Pleylist yükləndi",
        "Save error":"Yadda saxlamada xəta",
        "Open error":"Açmada xəta",
        "Add Media":"Media əlavə et",
        "Add Link":"Link əlavə et",
        "Enter Media URL:":"Media URL-ni daxil et:",
        "Pause":"Fasilə"
    },
    "bg_BG":{
        "Add":"Добавяне",
        "Remove":"Премахване",
        "Open":"Отваряне",
        "Play":"Възпроизвеждане",
        "Stop":"Спиране",
        "List":"Списък",
        "Party":"Парти",
        "Save Playlist":"Запази плейлист",
        "Open Playlist":"Отвори плейлист",
        "Playlist is empty":"Плейлистът е празен",
        "Playlist saved":"Плейлистът е запазен",
        "Playlist loaded":"Плейлистът е зареден",
        "Save error":"Грешка при запазване",
        "Open error":"Грешка при отваряне",
        "Add Media":"Добавяне на медия",
        "Add Link":"Добавяне на линк",
        "Enter Media URL:":"Въведете URL на медията:",
        "Pause":"Пауза"
    },
    "zh_CN":{
        "Add":"添加",
        "Remove":"删除",
        "Open":"打开",
        "Play":"播放",
        "Stop":"停止",
        "List":"列表",
        "Party":"派对",
        "Save Playlist":"保存播放列表",
        "Open Playlist":"打开播放列表",
        "Playlist is empty":"播放列表为空",
        "Playlist saved":"播放列表已保存",
        "Playlist loaded":"播放列表已加载",
        "Save error":"保存错误",
        "Open error":"打开错误",
        "Add Media":"添加媒体",
        "Add Link":"添加链接",
        "Enter Media URL:":"输入媒体 URL：",
        "Pause":"暂停"
    },
    "zh_TW":{
        "Add":"新增",
        "Remove":"刪除",
        "Open":"打開",
        "Play":"播放",
        "Stop":"停止",
        "List":"列表",
        "Party":"派對",
        "Save Playlist":"儲存播放清單",
        "Open Playlist":"打開播放清單",
        "Playlist is empty":"播放清單為空",
        "Playlist saved":"播放清單已儲存",
        "Playlist loaded":"播放清單已載入",
        "Save error":"儲存錯誤",
        "Open error":"打開錯誤",
        "Add Media":"新增媒體",
        "Add Link":"新增連結",
        "Enter Media URL:":"輸入媒體 URL：",
        "Pause":"暫停"
    },
    "hr_HR":{
        "Add":"Dodaj",
        "Remove":"Ukloni",
        "Open":"Otvori",
        "Play":"Reproduciraj",
        "Stop":"Zaustavi",
        "List":"Popis",
        "Party":"Žurka",
        "Save Playlist":"Spremi popis pjesama",
        "Open Playlist":"Otvori popis pjesama",
        "Playlist is empty":"Popis pjesama je prazan",
        "Playlist saved":"Popis pjesama spremljen",
        "Playlist loaded":"Popis pjesama učitan",
        "Save error":"Greška pri spremanju",
        "Open error":"Greška pri otvaranju",
        "Add Media":"Dodaj medij",
        "Add Link":"Dodaj poveznicu",
        "Enter Media URL:":"Unesite URL medija:",
        "Pause":"Pauza"
    },
    "cs_CZ":{
        "Add":"Přidat",
        "Remove":"Odstranit",
        "Open":"Otevřít",
        "Play":"Přehrát",
        "Stop":"Zastavit",
        "List":"Seznam",
        "Party":"Party",
        "Save Playlist":"Uložit seznam",
        "Open Playlist":"Otevřít seznam",
        "Playlist is empty":"Seznam je prázdný",
        "Playlist saved":"Seznam uložen",
        "Playlist loaded":"Seznam načten",
        "Save error":"Chyba při ukládání",
        "Open error":"Chyba při otevírání",
        "Add Media":"Přidat média",
        "Add Link":"Přidat odkaz",
        "Enter Media URL:":"Zadejte URL média:",
        "Pause":"Pozastavit"
    },
    "da_DK":{
        "Add":"Tilføj",
        "Remove":"Fjern",
        "Open":"Åbn",
        "Play":"Afspil",
        "Stop":"Stop",
        "List":"Liste",
        "Party":"Fest",
        "Save Playlist":"Gem playliste",
        "Open Playlist":"Åbn playliste",
        "Playlist is empty":"Playlisten er tom",
        "Playlist saved":"Playlisten gemt",
        "Playlist loaded":"Playlisten indlæst",
        "Save error":"Fejl ved gemning",
        "Open error":"Fejl ved åbning",
        "Add Media":"Tilføj medier",
        "Add Link":"Tilføj link",
        "Enter Media URL:":"Indtast medie URL:",
        "Pause":"Pause"
    },
    "nl_NL":{
        "Add":"Toevoegen",
        "Remove":"Verwijderen",
        "Open":"Openen",
        "Play":"Afspelen",
        "Stop":"Stoppen",
        "List":"Lijst",
        "Party":"Feest",
        "Save Playlist":"Sla afspeellijst op",
        "Open Playlist":"Open afspeellijst",
        "Playlist is empty":"Afspeellijst is leeg",
        "Playlist saved":"Afspeellijst opgeslagen",
        "Playlist loaded":"Afspeellijst geladen",
        "Save error":"Fout bij opslaan",
        "Open error":"Fout bij openen",
        "Add Media":"Media toevoegen",
        "Add Link":"Link toevoegen",
        "Enter Media URL:":"Voer media-URL in:",
        "Pause":"Pauze"
    },
    "en_US":{
        "Add":"Add",
        "Remove":"Remove",
        "Open":"Open",
        "Play":"Play",
        "Stop":"Stop",
        "List":"List",
        "Party":"Party",
        "Save Playlist":"Save Playlist",
        "Open Playlist":"Open Playlist",
        "Playlist is empty":"Playlist is empty",
        "Playlist saved":"Playlist saved",
        "Playlist loaded":"Playlist loaded",
        "Save error":"Save error",
        "Open error":"Open error",
        "Add Media":"Add Media",
        "Add Link":"Add Link",
        "Enter Media URL:":"Enter Media URL:",
        "Pause": "Pause"
    },
    "en_GB":{
        "Add":"Add",
        "Remove":"Remove",
        "Open":"Open",
        "Play":"Play",
        "Stop":"Stop",
        "List":"List",
        "Party":"Party",
        "Save Playlist":"Save Playlist",
        "Open Playlist":"Open Playlist",
        "Playlist is empty":"Playlist is empty",
        "Playlist saved":"Playlist saved",
        "Playlist loaded":"Playlist loaded",
        "Save error":"Save error",
        "Open error":"Open error",
        "Add Media":"Add Media",
        "Add Link":"Add Link",
        "Enter Media URL:":"Enter Media URL:",
        "Pause":"Pause"
    },
    "en_CA":{
        "Add":"Add",
        "Remove":"Remove",
        "Open":"Open",
        "Play":"Play",
        "Stop":"Stop",
        "List":"List",
        "Party":"Party",
        "Save Playlist":"Save Playlist",
        "Open Playlist":"Open Playlist",
        "Playlist is empty":"Playlist is empty",
        "Playlist saved":"Playlist saved",
        "Playlist loaded":"Playlist loaded",
        "Save error":"Save error",
        "Open error":"Open error",
        "Add Media":"Add Media",
        "Add Link":"Add Link",
        "Enter Media URL:":"Enter Media URL:",
        "Pause":"Pause"
    },
    "en_AU":{
        "Add":"Add",
        "Remove":"Remove",
        "Open":"Open",
        "Play":"Play",
        "Stop":"Stop",
        "List":"List",
        "Party":"Party",
        "Save Playlist":"Save Playlist",
        "Open Playlist":"Open Playlist",
        "Playlist is empty":"Playlist is empty",
        "Playlist saved":"Playlist saved",
        "Playlist loaded":"Playlist loaded",
        "Save error":"Save error",
        "Open error":"Open error",
        "Add Media":"Add Media",
        "Add Link":"Add Link",
        "Enter Media URL:":"Enter Media URL:",
        "Pause":"Pause"
    },
    "et_EE":{
        "Add":"Lisa",
        "Remove":"Eemalda",
        "Open":"Ava",
        "Play":"Esita",
        "Stop":"Peata",
        "List":"Nimekiri",
        "Party":"Pidu",
        "Save Playlist":"Salvesta esitusloend",
        "Open Playlist":"Ava esitusloend",
        "Playlist is empty":"Esitusloend on tühi",
        "Playlist saved":"Esitusloend salvestatud",
        "Playlist loaded":"Esitusloend laetud",
        "Save error":"Salvestamise viga",
        "Open error":"Avamise viga",
        "Add Media":"Lisa meedia",
        "Add Link":"Lisa link",
        "Enter Media URL:":"Sisesta meedia URL:",
        "Pause":"Pause"
    },
    "fi_FI":{
        "Add":"Lisää",
        "Remove":"Poista",
        "Open":"Avaa",
        "Play":"Toista",
        "Stop":"Pysäytä",
        "List":"Lista",
        "Party":"Juhla",
        "Save Playlist":"Tallenna soittolista",
        "Open Playlist":"Avaa soittolista",
        "Playlist is empty":"Soittolista on tyhjä",
        "Playlist saved":"Soittolista tallennettu",
        "Playlist loaded":"Soittolista ladattu",
        "Save error":"Tallennusvirhe",
        "Open error":"Avaa-virhe",
        "Add Media":"Lisää media",
        "Add Link":"Lisää linkki",
        "Enter Media URL:":"Syötä median URL:",
        "Pause":"Tauko"
    },
    "fr_FR":{
        "Add":"Ajouter",
        "Remove":"Supprimer",
        "Open":"Ouvrir",
        "Play":"Lire",
        "Stop":"Arrêter",
        "List":"Liste",
        "Party":"Fête",
        "Save Playlist":"Enregistrer la playlist",
        "Open Playlist":"Ouvrir la playlist",
        "Playlist is empty":"La playlist est vide",
        "Playlist saved":"Playlist enregistrée",
        "Playlist loaded":"Playlist chargée",
        "Save error":"Erreur d'enregistrement",
        "Open error":"Erreur d'ouverture",
        "Add Media":"Ajouter un média",
        "Add Link":"Ajouter un lien",
        "Enter Media URL:":"Entrez l'URL du média :",
        "Pause":"Pause"
    },
    "fr_CA":{
        "Add":"Ajouter",
        "Remove":"Supprimer",
        "Open":"Ouvrir",
        "Play":"Lire",
        "Stop":"Arrêter",
        "List":"Liste",
        "Party":"Fête",
        "Save Playlist":"Enregistrer la playlist",
        "Open Playlist":"Ouvrir la playlist",
        "Playlist is empty":"La playlist est vide",
        "Playlist saved":"Playlist enregistrée",
        "Playlist loaded":"Playlist chargée",
        "Save error":"Erreur d'enregistrement",
        "Open error":"Erreur d'ouverture",
        "Add Media":"Ajouter un média",
        "Add Link":"Ajouter un lien",
        "Enter Media URL:":"Entrez l'URL du média :",
        "Pause":"Pause"
    },
    "ka_GE":{
        "Add":"დამატება",
        "Remove":"წაშლა",
        "Open":"გახსნა",
        "Play":"გადართვა",
        "Stop":"შეჩერება",
        "List":"სია",
        "Party":"დაჭრა",
        "Save Playlist":"პლეილისტის შენახვა",
        "Open Playlist":"პლეილისტის გახსნა",
        "Playlist is empty":"პლეილისტი ცარიელია",
        "Playlist saved":"პლეილისტი შენახულია",
        "Playlist loaded":"პლეილისტი ჩატვირთულია",
        "Save error":"შენახვის შეცდომა",
        "Open error":"გახსნის შეცდომა",
        "Add Media":"მედიის დამატება",
        "Add Link":"ლინკის დამატება",
        "Enter Media URL:":"ჩასვით მედიის URL:",
        "Pause":"შეჩერება"
    },
    "de_DE":{
        "Add":"Hinzufügen",
        "Remove":"Entfernen",
        "Open":"Öffnen",
        "Play":"Abspielen",
        "Stop":"Stoppen",
        "List":"Liste",
        "Party":"Party",
        "Save Playlist":"Playlist speichern",
        "Open Playlist":"Playlist öffnen",
        "Playlist is empty":"Playlist ist leer",
        "Playlist saved":"Playlist gespeichert",
        "Playlist loaded":"Playlist geladen",
        "Save error":"Speicherfehler",
        "Open error":"Öffnungsfehler",
        "Add Media":"Medien hinzufügen",
        "Add Link":"Link hinzufügen",
        "Enter Media URL:":"Medien-URL eingeben:",
        "Pause":"Pause"
    },
    "el_GR":{
        "Add":"Προσθήκη",
        "Remove":"Αφαίρεση",
        "Open":"Άνοιγμα",
        "Play":"Αναπαραγωγή",
        "Stop":"Διακοπή",
        "List":"Λίστα",
        "Party":"Πάρτι",
        "Save Playlist":"Αποθήκευση λίστας αναπαραγωγής",
        "Open Playlist":"Άνοιγμα λίστας αναπαραγωγής",
        "Playlist is empty":"Η λίστα αναπαραγωγής είναι άδεια",
        "Playlist saved":"Η λίστα αναπαραγωγής αποθηκεύτηκε",
        "Playlist loaded":"Η λίστα αναπαραγωγής φορτώθηκε",
        "Save error":"Σφάλμα αποθήκευσης",
        "Open error":"Σφάλμα ανοίγματος",
        "Add Media":"Προσθήκη μέσων",
        "Add Link":"Προσθήκη συνδέσμου",
        "Enter Media URL:":"Εισάγετε το URL του μέσου:",
        "Pause":"Παύση"
    },
    "he_IL":{
        "Add":"הוסף",
        "Remove":"הסר",
        "Open":"פתח",
        "Play":"נגן",
        "Stop":"עצור",
        "List":"רשימה",
        "Party":"מסיבה",
        "Save Playlist":"שמור רשימת השמעה",
        "Open Playlist":"פתח רשימת השמעה",
        "Playlist is empty":"רשימת ההשמעה ריקה",
        "Playlist saved":"רשימת ההשמעה נשמרה",
        "Playlist loaded":"רשימת ההשמעה נטענה",
        "Save error":"שגיאת שמירה",
        "Open error":"שגיאת פתיחה",
        "Add Media":"הוסף מדיה",
        "Add Link":"הוסף קישור",
        "Enter Media URL:":"הכנס URL מדיה:",
        "Pause":"השהה"
    },
    "hi_IN":{
        "Add":"जोड़ें",
        "Remove":"हटाएँ",
        "Open":"खोलें",
        "Play":"चलाएँ",
        "Stop":"बंद करें",
        "List":"सूची",
        "Party":"पार्टी",
        "Save Playlist":"प्लेलिस्ट सहेजें",
        "Open Playlist":"प्लेलिस्ट खोलें",
        "Playlist is empty":"प्लेलिस्ट खाली है",
        "Playlist saved":"प्लेलिस्ट सहेजी गई",
        "Playlist loaded":"प्लेलिस्ट लोड की गई",
        "Save error":"सहेजने में त्रुटि",
        "Open error":"खोलने में त्रुटि",
        "Add Media":"मीडिया जोड़ें",
        "Add Link":"लिंक जोड़ें",
        "Enter Media URL:":"मीडिया URL दर्ज करें:",
        "Pause":"रोकें"
    },
    "hu_HU":{
        "Add":"Hozzáadás",
        "Remove":"Eltávolítás",
        "Open":"Megnyitás",
        "Play":"Lejátszás",
        "Stop":"Megállítás",
        "List":"Lista",
        "Party":"Buli",
        "Save Playlist":"Lejátszási lista mentése",
        "Open Playlist":"Lejátszási lista megnyitása",
        "Playlist is empty":"A lejátszási lista üres",
        "Playlist saved":"Lejátszási lista mentve",
        "Playlist loaded":"Lejátszási lista betöltve",
        "Save error":"Mentési hiba",
        "Open error":"Megnyitási hiba",
        "Add Media":"Média hozzáadása",
        "Add Link":"Link hozzáadása",
        "Enter Media URL:":"Média URL megadása:",
        "Pause":"Szünet"
    },
    "it_IT":{
        "Add":"Aggiungi",
        "Remove":"Rimuovi",
        "Open":"Apri",
        "Play":"Riproduci",
        "Stop":"Ferma",
        "List":"Elenco",
        "Party":"Festa",
        "Save Playlist":"Salva playlist",
        "Open Playlist":"Apri playlist",
        "Playlist is empty":"La playlist è vuota",
        "Playlist saved":"Playlist salvata",
        "Playlist loaded":"Playlist caricata",
        "Save error":"Errore di salvataggio",
        "Open error":"Errore di apertura",
        "Add Media":"Aggiungi media",
        "Add Link":"Aggiungi link",
        "Enter Media URL:":"Inserisci URL media:",
        "Pause":"Pausa"
    },
    "ja_JP":{
        "Add":"追加",
        "Remove":"削除",
        "Open":"開く",
        "Play":"再生",
        "Stop":"停止",
        "List":"リスト",
        "Party":"パーティー",
        "Save Playlist":"プレイリストを保存",
        "Open Playlist":"プレイリストを開く",
        "Playlist is empty":"プレイリストは空です",
        "Playlist saved":"プレイリストを保存しました",
        "Playlist loaded":"プレイリストを読み込みました",
        "Save error":"保存エラー",
        "Open error":"開くエラー",
        "Add Media":"メディアを追加",
        "Add Link":"リンクを追加",
        "Enter Media URL:":"メディアのURLを入力：",
        "Pause":"一時停止"
    },
    "kk_KZ":{
        "Add":"Қосу",
        "Remove":"Жою",
        "Open":"Ашу",
        "Play":"Ойнату",
        "Stop":"Тоқтату",
        "List":"Тізім",
        "Party":"Пати",
        "Save Playlist":"Ойнату тізімін сақтау",
        "Open Playlist":"Ойнату тізімін ашу",
        "Playlist is empty":"Ойнату тізімі бос",
        "Playlist saved":"Ойнату тізімі сақталды",
        "Playlist loaded":"Ойнату тізімі жүктелді",
        "Save error":"Сақтауда қате",
        "Open error":"Ашу кезінде қате",
        "Add Media":"Медиа қосу",
        "Add Link":"Сілтеме қосу",
        "Enter Media URL:":"Медиа URL енгізіңіз:",
        "Pause":"Уақытша тоқтату"
    },
    "ko_KR":{
        "Add":"추가",
        "Remove":"제거",
        "Open":"열기",
        "Play":"재생",
        "Stop":"정지",
        "List":"목록",
        "Party":"파티",
        "Save Playlist":"재생목록 저장",
        "Open Playlist":"재생목록 열기",
        "Playlist is empty":"재생목록이 비었습니다",
        "Playlist saved":"재생목록 저장됨",
        "Playlist loaded":"재생목록 불러옴",
        "Save error":"저장 오류",
        "Open error":"열기 오류",
        "Add Media":"미디어 추가",
        "Add Link":"링크 추가",
        "Enter Media URL:":"미디어 URL 입력:",
        "Pause":"일시정지"
    },
    "ky_KG":{
        "Add":"Кошуу",
        "Remove":"Жок кылуу",
        "Open":"Ачуу",
        "Play":"Ойнотуу",
        "Stop":"Токтотуу",
        "List":"Тизмек",
        "Party":"Байрам",
        "Save Playlist":"Ойноп жаткан тизмекти сактоо",
        "Open Playlist":"Ойноп жаткан тизмекти ачуу",
        "Playlist is empty":"Тизмек бош",
        "Playlist saved":"Тизмек сакталды",
        "Playlist loaded":"Тизмек жүктөлдү",
        "Save error":"Сактоодо ката",
        "Open error":"Ачууда ката",
        "Add Media":"Медиа кошуу",
        "Add Link":"Ссылка кошуу",
        "Enter Media URL:":"Медиа URL киргизүү:",
        "Pause":"Убактылуу токтотуу"
    },
    "lv_LV":{
        "Add":"Pievienot",
        "Remove":"Noņemt",
        "Open":"Atvērt",
        "Play":"Atskaņot",
        "Stop":"Apturēt",
        "List":"Saraksts",
        "Party":"Ballīte",
        "Save Playlist":"Saglabāt atskaņošanas sarakstu",
        "Open Playlist":"Atvērt atskaņošanas sarakstu",
        "Playlist is empty":"Atskaņošanas saraksts ir tukšs",
        "Playlist saved":"Atskaņošanas saraksts saglabāts",
        "Playlist loaded":"Atskaņošanas saraksts ielādēts",
        "Save error":"Saglabāšanas kļūda",
        "Open error":"Atvēršanas kļūda",
        "Add Media":"Pievienot multivides failu",
        "Add Link":"Pievienot saiti",
        "Enter Media URL:":"Ievadiet multivides URL:",
        "Pause":"Pauze"
    },
    "lt_LT":{
        "Add":"Pridėti",
        "Remove":"Pašalinti",
        "Open":"Atidaryti",
        "Play":"Leisti",
        "Stop":"Sustabdyti",
        "List":"Sąrašas",
        "Party":"Šventė",
        "Save Playlist":"Išsaugoti grojaraštį",
        "Open Playlist":"Atidaryti grojaraštį",
        "Playlist is empty":"Grojaraštis tuščias",
        "Playlist saved":"Grojaraštis išsaugotas",
        "Playlist loaded":"Grojaraštis įkeltas",
        "Save error":"Klaida išsaugant",
        "Open error":"Klaida atidarant",
        "Add Media":"Pridėti mediją",
        "Add Link":"Pridėti nuorodą",
        "Enter Media URL:":"Įveskite medijos URL:",
        "Pause":"Pauzė"
    },
    "mn_MN":{
        "Add":"Нэмэх",
        "Remove":"Устгах",
        "Open":"Нээх",
        "Play":"Тоглуулах",
        "Stop":"Зогсоох",
        "List":"Жагсаалт",
        "Party":"Үдэшлэг",
        "Save Playlist":"Жагсаалтыг хадгалах",
        "Open Playlist":"Жагсаалтыг нээх",
        "Playlist is empty":"Жагсаалт хоосон байна",
        "Playlist saved":"Жагсаалт хадгалагдсан",
        "Playlist loaded":"Жагсаалт ачаалагдсан",
        "Save error":"Хадгалах алдаа",
        "Open error":"Нээх алдаа",
        "Add Media":"Медиа нэмэх",
        "Add Link":"Холбоос нэмэх",
        "Enter Media URL:":"Медиа URL оруулах:",
        "Pause":"Зогсоох"
    },
    "fa_IR":{
        "Add":"افزودن",
        "Remove":"حذف",
        "Open":"باز کردن",
        "Play":"پخش",
        "Stop":"توقف",
        "List":"لیست",
        "Party":"مهمانی",
        "Save Playlist":"ذخیره فهرست پخش",
        "Open Playlist":"باز کردن فهرست پخش",
        "Playlist is empty":"فهرست پخش خالی است",
        "Playlist saved":"فهرست پخش ذخیره شد",
        "Playlist loaded":"فهرست پخش بارگذاری شد",
        "Save error":"خطای ذخیره‌سازی",
        "Open error":"خطای باز کردن",
        "Add Media":"افزودن رسانه",
        "Add Link":"افزودن لینک",
        "Enter Media URL:":"URL رسانه را وارد کنید:",
        "Pause":"توقف"
    },
    "pl_PL":{
        "Add":"Dodaj",
        "Remove":"Usuń",
        "Open":"Otwórz",
        "Play":"Odtwórz",
        "Stop":"Zatrzymaj",
        "List":"Lista",
        "Party":"Impreza",
        "Save Playlist":"Zapisz listę odtwarzania",
        "Open Playlist":"Otwórz listę odtwarzania",
        "Playlist is empty":"Lista odtwarzania jest pusta",
        "Playlist saved":"Lista odtwarzania zapisana",
        "Playlist loaded":"Lista odtwarzania załadowana",
        "Save error":"Błąd zapisu",
        "Open error":"Błąd otwarcia",
        "Add Media":"Dodaj multimedia",
        "Add Link":"Dodaj link",
        "Enter Media URL:":"Wprowadź URL multimediów:",
        "Pause":"Pauza"
    },
    "pt_PT":{
        "Add":"Adicionar",
        "Remove":"Remover",
        "Open":"Abrir",
        "Play":"Reproduzir",
        "Stop":"Parar",
        "List":"Lista",
        "Party":"Festa",
        "Save Playlist":"Guardar lista de reprodução",
        "Open Playlist":"Abrir lista de reprodução",
        "Playlist is empty":"A lista de reprodução está vazia",
        "Playlist saved":"Lista de reprodução guardada",
        "Playlist loaded":"Lista de reprodução carregada",
        "Save error":"Erro ao guardar",
        "Open error":"Erro ao abrir",
        "Add Media":"Adicionar mídia",
        "Add Link":"Adicionar link",
        "Enter Media URL:":"Introduza a URL da mídia:",
        "Pause":"Pausa"
    },
    "pt_BR":{
        "Add":"Adicionar",
        "Remove":"Remover",
        "Open":"Abrir",
        "Play":"Reproduzir",
        "Stop":"Parar",
        "List":"Lista",
        "Party":"Festa",
        "Save Playlist":"Salvar playlist",
        "Open Playlist":"Abrir playlist",
        "Playlist is empty":"Playlist está vazia",
        "Playlist saved":"Playlist salva",
        "Playlist loaded":"Playlist carregada",
        "Save error":"Erro ao salvar",
        "Open error":"Erro ao abrir",
        "Add Media":"Adicionar mídia",
        "Add Link":"Adicionar link",
        "Enter Media URL:":"Digite a URL da mídia:",
        "Pause":"Pausa"
    },
    "ro_RO":{
        "Add":"Adaugă",
        "Remove":"Elimină",
        "Open":"Deschide",
        "Play":"Redă",
        "Stop":"Oprește",
        "List":"Listă",
        "Party":"Petrecere",
        "Save Playlist":"Salvează lista de redare",
        "Open Playlist":"Deschide lista de redare",
        "Playlist is empty":"Lista de redare este goală",
        "Playlist saved":"Lista de redare a fost salvată",
        "Playlist loaded":"Lista de redare a fost încărcată",
        "Save error":"Eroare la salvare",
        "Open error":"Eroare la deschidere",
        "Add Media":"Adaugă media",
        "Add Link":"Adaugă link",
        "Enter Media URL:":"Introduceți URL-ul media:",
        "Pause":"Pauză"
    },
    "ru_RU":{
        "Add":"Добавить",
        "Remove":"Удалить",
        "Open":"Открыть",
        "Play":"Воспроизвести",
        "Stop":"Стоп",
        "List":"Список",
        "Party":"Вечеринка",
        "Save Playlist":"Сохранить плейлист",
        "Open Playlist":"Открыть плейлист",
        "Playlist is empty":"Плейлист пуст",
        "Playlist saved":"Плейлист сохранен",
        "Playlist loaded":"Плейлист загружен",
        "Save error":"Ошибка сохранения",
        "Open error":"Ошибка открытия",
        "Add Media":"Добавить медиа",
        "Add Link":"Добавить ссылку",
        "Enter Media URL:":"Введите URL медиа:",
        "Pause":"Пауза"
    },
    "sr_RS":{
        "Add":"Додај",
        "Remove":"Уклони",
        "Open":"Отвори",
        "Play":"Пусти",
        "Stop":"Стоп",
        "List":"Листа",
        "Party":"Журка",
        "Save Playlist":"Сачувај листу",
        "Open Playlist":"Отвори листу",
        "Playlist is empty":"Листа је празна",
        "Playlist saved":"Листа сачувана",
        "Playlist loaded":"Листа учитана",
        "Save error":"Грешка при чувању",
        "Open error":"Грешка при отварању",
        "Add Media":"Додај медија",
        "Add Link":"Додај линк",
        "Enter Media URL:":"Унесите URL медија:",
        "Pause":"Пауза"
    },
    "sr_RS_latin":{
        "Add":"Dodaj",
        "Remove":"Ukloni",
        "Open":"Otvori",
        "Play":"Pusti",
        "Stop":"Stop",
        "List":"Lista",
        "Party":"Žurka",
        "Save Playlist":"Sačuvaj listu",
        "Open Playlist":"Otvori listu",
        "Playlist is empty":"Lista je prazna",
        "Playlist saved":"Lista sačuvana",
        "Playlist loaded":"Lista učitana",
        "Save error":"Greška pri čuvanju",
        "Open error":"Greška pri otvaranju",
        "Add Media":"Dodaj medija",
        "Add Link":"Dodaj link",
        "Enter Media URL:":"Unesite URL medija:",
        "Pause":"Pauza"
    },
    "sk_SK":{
        "Add":"Pridať",
        "Remove":"Odstrániť",
        "Open":"Otvoriť",
        "Play":"Prehrať",
        "Stop":"Zastaviť",
        "List":"Zoznam",
        "Party":"Párty",
        "Save Playlist":"Uložiť zoznam skladieb",
        "Open Playlist":"Otvoriť zoznam skladieb",
        "Playlist is empty":"Zoznam skladieb je prázdny",
        "Playlist saved":"Zoznam skladieb uložený",
        "Playlist loaded":"Zoznam skladieb načítaný",
        "Save error":"Chyba pri ukladaní",
        "Open error":"Chyba pri otváraní",
        "Add Media":"Pridať médiá",
        "Add Link":"Pridať odkaz",
        "Enter Media URL:":"Zadajte URL médií:",
        "Pause":"Pauza"
    },
    "sl_SI":{
        "Add":"Dodaj",
        "Remove":"Odstrani",
        "Open":"Odpri",
        "Play":"Predvajaj",
        "Stop":"Ustavi",
        "List":"Seznam",
        "Party":"Zabava",
        "Save Playlist":"Shrani predvajalni seznam",
        "Open Playlist":"Odpri predvajalni seznam",
        "Playlist is empty":"Predvajalni seznam je prazen",
        "Playlist saved":"Predvajalni seznam shranjen",
        "Playlist loaded":"Predvajalni seznam naložen",
        "Save error":"Napaka pri shranjevanju",
        "Open error":"Napaka pri odpiranju",
        "Add Media":"Dodaj medije",
        "Add Link":"Dodaj povezavo",
        "Enter Media URL:":"Vnesite URL medija:",
        "Pause":"Premor"
    },
    "es_ES":{
        "Add":"Añadir",
        "Remove":"Eliminar",
        "Open":"Abrir",
        "Play":"Reproducir",
        "Stop":"Detener",
        "List":"Lista",
        "Party":"Fiesta",
        "Save Playlist":"Guardar lista de reproducción",
        "Open Playlist":"Abrir lista de reproducción",
        "Playlist is empty":"La lista de reproducción está vacía",
        "Playlist saved":"Lista de reproducción guardada",
        "Playlist loaded":"Lista de reproducción cargada",
        "Save error":"Error al guardar",
        "Open error":"Error al abrir",
        "Add Media":"Añadir medios",
        "Add Link":"Añadir enlace",
        "Enter Media URL:":"Introduce la URL del medio:",
        "Pause":"Pausa"
    },
    "sv_SE":{
        "Add":"Lägg till",
        "Remove":"Ta bort",
        "Open":"Öppna",
        "Play":"Spela",
        "Stop":"Stoppa",
        "List":"Lista",
        "Party":"Fest",
        "Save Playlist":"Spara spellista",
        "Open Playlist":"Öppna spellista",
        "Playlist is empty":"Spellistan är tom",
        "Playlist saved":"Spellistan sparad",
        "Playlist loaded":"Spellistan laddad",
        "Save error":"Fel vid sparande",
        "Open error":"Fel vid öppning",
        "Add Media":"Lägg till media",
        "Add Link":"Lägg till länk",
        "Enter Media URL:":"Ange mediens URL:",
        "Pause":"Paus"
    },
    "tt_RU":{
        "Add":"Өстәргә",
        "Remove":"Бетерергә",
        "Open":"Ачу",
        "Play":"Уйнарга",
        "Stop":"Туктатырга",
        "List":"Рәсемлек",
        "Party":"Җыелыш",
        "Save Playlist":"Рәсемлекне саклау",
        "Open Playlist":"Рәсемлекне ачу",
        "Playlist is empty":"Рәсемлек буш",
        "Playlist saved":"Рәсемлек сакланды",
        "Playlist loaded":"Рәсемлек йөкләнде",
        "Save error":"Саклауда хата",
        "Open error":"Ачуда хата",
        "Add Media":"Медиа өстәү",
        "Add Link":"Сылтама өстәү",
        "Enter Media URL:":"Медиа URL кертергә:",
        "Pause":"Туктату"
    },
    "th_TH":{
        "Add":"เพิ่ม",
        "Remove":"ลบ",
        "Open":"เปิด",
        "Play":"เล่น",
        "Stop":"หยุด",
        "List":"รายการ",
        "Party":"ปาร์ตี้",
        "Save Playlist":"บันทึกรายการเพลง",
        "Open Playlist":"เปิดรายการเพลง",
        "Playlist is empty":"รายการเพลงว่าง",
        "Playlist saved":"บันทึกรายการเพลงแล้ว",
        "Playlist loaded":"โหลดรายการเพลงแล้ว",
        "Save error":"ข้อผิดพลาดในการบันทึก",
        "Open error":"ข้อผิดพลาดในการเปิด",
        "Add Media":"เพิ่มสื่อ",
        "Add Link":"เพิ่มลิงก์",
        "Enter Media URL:":"ใส่ URL สื่อ:",
        "Pause":"หยุดชั่วคราว"
    },
    "bo_CN":{
        "Add":"ཀུན་བཀོད",
        "Remove":"བཏོན་བཀོད",
        "Open":"ཁུངས་སྒྲིག",
        "Play":"བརྒྱབ",
        "Stop":"བརྗེད",
        "List":"སྡེ་ཚན",
        "Party":"དགའ་སྟོན",
        "Save Playlist":"གསར་བཟོས་སྐུལ་བྱེད",
        "Open Playlist":"གསར་བཟོས་ཁ་བཏང",
        "Playlist is empty":"གསར་བཟོས་སྡེ་ཚན་ལྡོག་ཡོད",
        "Playlist saved":"གསར་བཟོས་སྡེ་ཚན་བསྡུས་པ",
        "Playlist loaded":"གསར་བཟོས་སྡེ་ཚན་འཕྲིན་པ",
        "Save error":"གསར་བཟོས་བྱེད་སྤྲོད་ནུབ",
        "Open error":"ཁ་བཏང་སྤྲོད་ནུབ",
        "Add Media":"སྒྲིག་འཕྲིན་ཀུན་བཀོད",
        "Add Link":"རྩོམ་འབྲེལ་ཀུན་བཀོད",
        "Enter Media URL:":"སྒྲིག་འཕྲིན URL ཐོག་བཙུགས།",
        "Pause":"ཕྱིན་མཐུན"
    },
    "tr_TR":{
        "Add":"Ekle",
        "Remove":"Kaldır",
        "Open":"Aç",
        "Play":"Oynat",
        "Stop":"Durdur",
        "List":"Liste",
        "Party":"Parti",
        "Save Playlist":"Oynatma listesini kaydet",
        "Open Playlist":"Oynatma listesini aç",
        "Playlist is empty":"Oynatma listesi boş",
        "Playlist saved":"Oynatma listesi kaydedildi",
        "Playlist loaded":"Oynatma listesi yüklendi",
        "Save error":"Kaydetme hatası",
        "Open error":"Açma hatası",
        "Add Media":"Medya ekle",
        "Add Link":"Bağlantı ekle",
        "Enter Media URL:":"Medya URL'sini girin:",
        "Pause":"Duraklat"
    },
    "tk_TM":{
        "Add":"Goşmak",
        "Remove":"Aýyrmak",
        "Open":"Açmak",
        "Play":"Oýnatmak",
        "Stop":"Durmak",
        "List":"Sanaw",
        "Party":"Parti",
        "Save Playlist":"Sanawy saklamak",
        "Open Playlist":"Sanawy açmak",
        "Playlist is empty":"Sanaw boş",
        "Playlist saved":"Sanaw saklanyldy",
        "Playlist loaded":"Sanaw ýüklenildi",
        "Save error":"Saklamakda säwlik",
        "Open error":"Açmakda säwlik",
        "Add Media":"Mediany goşmak",
        "Add Link":"Baglanyşygy goşmak",
        "Enter Media URL:":"Medya URL-ni giriziň:",
        "Pause":"Durdur"
    },
    "uk_UA":{
        "Add":"Додати",
        "Remove":"Видалити",
        "Open":"Відкрити",
        "Play":"Відтворити",
        "Stop":"Зупинити",
        "List":"Список",
        "Party":"Вечірка",
        "Save Playlist":"Зберегти плейлист",
        "Open Playlist":"Відкрити плейлист",
        "Playlist is empty":"Плейлист порожній",
        "Playlist saved":"Плейлист збережено",
        "Playlist loaded":"Плейлист завантажено",
        "Save error":"Помилка збереження",
        "Open error":"Помилка відкриття",
        "Add Media":"Додати медіа",
        "Add Link":"Додати посилання",
        "Enter Media URL:":"Введіть URL медіа:",
        "Pause":"Пауза"
    },
    "ur_PK":{
        "Add":"شامل کریں",
        "Remove":"ہٹائیں",
        "Open":"کھولیں",
        "Play":"چلائیں",
        "Stop":"روکیں",
        "List":"فہرست",
        "Party":"پارٹی",
        "Save Playlist":"پلے لسٹ محفوظ کریں",
        "Open Playlist":"پلے لسٹ کھولیں",
        "Playlist is empty":"پلے لسٹ خالی ہے",
        "Playlist saved":"پلے لسٹ محفوظ ہوگئی",
        "Playlist loaded":"پلے لسٹ لوڈ ہوگئی",
        "Save error":"محفوظ کرنے میں خرابی",
        "Open error":"کھولنے میں خرابی",
        "Add Media":"میڈیا شامل کریں",
        "Add Link":"لنک شامل کریں",
        "Enter Media URL:":"میڈیا URL درج کریں:",
        "Pause":"وقفہ"
    },
    "ug_CN":{
        "Add":"قوشۇش",
        "Remove":"چىقىرىش",
        "Open":"ئاچىش",
        "Play":"كۆرۈش",
        "Stop":"توختىتىش",
        "List":"تىزىملىك",
        "Party":"پارتىيە",
        "Save Playlist":"تىزىملىكنى ساقلاش",
        "Open Playlist":"تىزىملىكنى ئاچىش",
        "Playlist is empty":"تىزىملىك بوش",
        "Playlist saved":"تىزىملىك ساقلانغان",
        "Playlist loaded":"تىزىملىك يۈكلەنگەن",
        "Save error":"ساقلاشدا خاتالىق",
        "Open error":"ئاچقۇچتا خاتالىق",
        "Add Media":"مىدىيانى قوشۇش",
        "Add Link":"ئۇلانمىنى قوشۇش",
        "Enter Media URL:":"مىدىيا URL نى كىرگۈزۈڭ:",
        "Pause":"توختات"
    },
    "uz_UZ":{
        "Add":"Qoʻshish",
        "Remove":"Oʻchirish",
        "Open":"Ochish",
        "Play":"Oʻynatish",
        "Stop":"Toʻxtatish",
        "List":"Roʻyxat",
        "Party":"Bayram",
        "Save Playlist":"Roʻyxatni saqlash",
        "Open Playlist":"Roʻyxatni ochish",
        "Playlist is empty":"Roʻyxat boʻsh",
        "Playlist saved":"Roʻyxat saqlandi",
        "Playlist loaded":"Roʻyxat yuklandi",
        "Save error":"Saqlashda xato",
        "Open error":"Ochishda xato",
        "Add Media":"Media qoʻshish",
        "Add Link":"Havola qoʻshish",
        "Enter Media URL:":"Media URL kiriting:",
        "Pause":"Toʻxtatish"
    },
    "vi_VN":{
        "Add":"Thêm",
        "Remove":"Xóa",
        "Open":"Mở",
        "Play":"Phát",
        "Stop":"Dừng",
        "List":"Danh sách",
        "Party":"Tiệc",
        "Save Playlist":"Lưu danh sách phát",
        "Open Playlist":"Mở danh sách phát",
        "Playlist is empty":"Danh sách phát trống",
        "Playlist saved":"Danh sách phát đã lưu",
        "Playlist loaded":"Danh sách phát đã tải",
        "Save error":"Lỗi lưu",
        "Open error":"Lỗi mở",
        "Add Media":"Thêm phương tiện",
        "Add Link":"Thêm liên kết",
        "Enter Media URL:":"Nhập URL phương tiện:",
        "Pause":"Tạm dừng"
    }
}
